version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
        - "8000:8000"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/

volumes:
  static_value:
  media_value: